version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "07:00"
    open-pull-requests-limit: 99
    labels:
      - dependencies
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "07:00"
    open-pull-requests-limit: 99
    labels:
      - dependencies
