version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "07:00"
    open-pull-requests-limit: 99
    labels:
      - dependencies
    ignore:
      - dependency-name: simplecov
        versions:
          - ">= 0.18"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "07:00"
    open-pull-requests-limit: 99
    labels:
      - dependencies
