AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Lint/EndAlignment:
  Enabled: true

Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/flip_fab/persistence.rb'

Metrics/AbcSize:
  Exclude:
    - 'spec/support/test_app.rb'

Metrics/LineLength:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - 'spec/lib/flip_fab/contextual_feature_spec.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'example/rails_app/test/test_helper.rb'

Style/Documentation:
  Enabled: false

