inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Lint/EndAlignment:
  Enabled: true

Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/flip_fab/persistence.rb'
