name: Create GitHub Release

on:
  push:
    branches:
      - "master"

permissions:
  contents: write

jobs:
  create-new-release:
    uses: simplybusiness/github-action-reusable-workflows/.github/workflows/create-github-release.yaml@v1
    with:
      gem_version_class: "AbFab::VERSION"
    secrets:
      bnw-registry-user: ${{ secrets.GH_ACTIONS_NEXUS_USER }}
      bnw-registry-password: ${{ secrets.GH_ACTIONS_NEXUS_PASSWORD }}
