name: Integration Build

on:
  push:
    branches-ignore:
      - 'master'

env:
  REPOSITORY: "flip_fab"

concurrency: huxley-ci-${{ github.ref }}

jobs:
  Build_Gem:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id    : ${{ secrets.AWS_LIVE_CICD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_LIVE_CICD_SECRET_ACCESS_KEY }}
          aws-region           : ${{ secrets.AWS_LIVE_CICD_REGION }}
      - name: Build Gem
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: ${{ env.REPOSITORY }}
          buildspec-override: _pipeline/stage_build_gem.yml
