name: Check version

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

permissions:
  contents: read
  statuses: write

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: simplybusiness/version-forget-me-not@v2
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_FILE_PATH: "lib/ab_fab/version.rb"
